# Generated by Django 3.2 on 2021-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio_information',
            field=models.TextField(help_text='Enter a biographical information about the blogger/author', max_length=1000, null=True),
        ),
    ]
