# Generated by Django 3.2 on 2021-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogger_bio_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio_information',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
